### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by dsplvd** [pocopico/rp-ext#1]
First of all, thank you for your great work. Thanks to your ramdisk images I could boot redpill in my gen7 microserver (can't install, stuck at recovery loop, baby steps I guess)

I'm trying to use your tg3 modules, but I can't get to work:

[!] Checksum mismatch - expected 58ac47ce41eb1e813120e4f3f323229018d91d15f75d29c1750c74dc9df2e236 but computed 8947f9c55c4aeb45fca61492f64dac29a72c21ce9b845a90fd357c46c79399e1

I edited the files directly to jump this step but doesn't work either

**Comment by pocopico** [comment]
Fixed, checksum : 8947f9c55c4aeb45fca61492f64dac29a72c21ce9b845a90fd357c46c79399e1
