### ISSUE TITLE
powerbutton or qemu-guest-agent for dsm7

### ISSUE THREAD

**Issue by ghost** [pocopico/rp-ext#10]
Is it possible to make powerbuttom or qemu-guest-agent run on the DSM 7，so we can use power off or restart button on proxmox host

**Comment by pocopico** [comment]
Already at Jumkey repository

https://github.com/jumkey/redpill-load/blob/develop/redpill-acpid/rpext-index.json

**Comment by zz0770** [comment]
it not work on pve7.1
