### ISSUE TITLE
Failed to add "https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json" as an extension:

### ISSUE THREAD

**Issue by eason666888** [pocopico/rp-ext#101]
Failed to download https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json to /opt/redpill-load/custom/extensions/_new_ext_index.tmp_json

*** Process will exit ***

[!] Failed to add "https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json" as an extension:

,

*** Process will exit ***
[!] Failed to install redpill.bootwait bundled extension - see errors above

*** Process will exit ***

**Comment by pocopico** [comment]
Not very descriptive, please post a descriptive message
