### ISSUE TITLE
Please add 10G card driver, "HP 560SFP+"

### ISSUE THREAD

**Issue by klaaut** [pocopico/rp-ext#103]
HI, 
Thank you again for your kind support.
Would you please add HP 560SFP+ 10G lan driver also?  It can not recognized at the first TC install stage.. but since TC installed, it's regcognized when I install this card into my system... but it's looks unstable...
I'll be very appriciate if you make this lan card driver also... 

Best regards

**Comment by klaaut** [comment]
for more detail informatin,
With 560SFP+ install when the first install stage, TC have successfully built even the network status unstable..
after that, when I tride to found out the sysnology on my notebook, it's disapeared...
(I already done add the ixgbe ext... https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe.vanilla/rpext-index.json)

So I should have to install TC with board internal lan adapter... after successfully installed the TC, then I put my 560SFP+ into the system.. then TC well recognized the 560SFP+... but it still unstable .. on the network...

**Comment by klaaut** [comment]
Here is my log for your infromation,

SynologyNAS> cat /var/log/junior_reason
Exit on error [99] rp ext init exec failure...

SynologyNAS> cat /var/log/*rc*
START /linuxrc.syno.impl
Insert Marvell 1475 SATA controller driver
Insert basic USB modules...
:: Loading module usb-common ... [  OK  ]
:: Loading module usbcore ... [  OK  ]
:: Loading module ehci-hcd ... [  OK  ]
:: Loading module ehci-pci ... [  OK  ]
:: Loading module xhci-hcd ... [  OK  ]
:: Loading module xhci-pci ... [  OK  ]
:: Loading module usb-storage ... [  OK  ]
:: Loading kernel modules from extensions ...
Loading kmod #0 "arcmsr.ko" for pocopico.arcmsr (args: )
Loading kmod #0 "dca.ko" for pocopico.igb (args: )
Loading kmod #1 "igb.ko" for pocopico.igb (args: )
Loading kmod #0 "udp_tunnel.ko" for pocopico.ixgbe (args: )
Loading kmod #1 "ip6_udp_tunnel.ko" for pocopico.ixgbe (args: )
Loading kmod #2 "dca.ko" for pocopico.ixgbe (args: )
insmod: can't insert 'dca.ko': File exists
ERROR: kernel extensions "dca.ko" from pocopico.ixgbe failed to load
Exit on error [99] rp ext init exec failure...
Mon Apr 25 04:44:04 UTC 2022
none /sys/kernel/debug debugfs rw,relatime 0 0
SynologyNAS>

**Comment by PeterSuh-Q3** [comment]
Pocopico,

I remember last time on the Henology forum you gave the answer below regarding this phenomenon.

**"When you load extension that use overlapping dependencies the initial script will fail. I modified the script to load the module only if it’s not loaded."**

---------------------------------------------------------------

So the built-in igb NIC controller was disabled in the BIOS so as not to conflict with the built-in igb,
In this case, there is a problem that ixgbe cannot start LAN by itself.

Because klaaut cannot upload the log that removed igb
In the state that you know that you should not use two igb / ixgbe
He had no choice but to log this.

**Comment by pocopico** [comment]
You have to use the pocopico repo For your loader

**Comment by klaaut** [comment]
Thank you very much, pocopico!
I'm confused little bit for 'use the pocopico repo' mean..

And now I make disable mobo's internal 1G lan.  Then install my 560SFP+ and tried again to avoid duplex crash... it still good for the kernel build stage... but after rebooting, it's disapeared from the network and can not find out sysnology diskstation within Lan...

**Comment by pocopico** [comment]
Actually you only need one network extension for installing. The ixgbe is included in vanilla DSM

**Comment by klaaut** [comment]
Thank you very much pocopico.
Based on you comment, I'vd done this 
 "./rploader.sh ext broadwellnk-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe.vanilla/rpext-index.json "

and try to compile kernel.  but it failed with below message..

############################################################################################ 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/pocopico.arcmsr/ds3622xsp_42218/check-arcmsr.sh file... [OK]
[#] Successfully processed recipe for extension pocopico.arcmsr platform ds3622xsp_42218
[-] The extension pocopico.ixgbe.vanilla was found. However, the extension index has no recipe for ds3622xsp_42218 platform. It may not be
[-] supported on that platform, or author didn't updated it for that platform yet. You can try running
[-] "ext-manager.sh update" to refresh indexes for all extensions manually. Below are the currently known information about
[-] the extension stored locally:
[#] ========================================== pocopico.ixgbe.vanilla ==========================================
[#] Extension name: ixgbe
[#] Description: Adds Intel(R) 10GbE PCI Express Linux Network Driver Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/ixgbe.vanilla
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe.vanilla/rpext-index.json
[#] Platforms supported: ds3615xs_42218
[#] =======================================================================================

[-] Failed to update recipe for pocopico.ixgbe.vanilla extension for platform ds3622xsp_42218. The script will terminate as you do not
[-] have previously downloaded recipe which can be used if download fails. Try again later. If problem
[-] persists contact the extension packer for support (displayed below)
[#] ========================================== pocopico.ixgbe.vanilla ==========================================
[#] Extension name: ixgbe
[#] Description: Adds Intel(R) 10GbE PCI Express Linux Network Driver Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/ixgbe.vanilla
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe.vanilla/rpext-index.json
[#] Platforms supported: ds3615xs_42218
[#] =======================================================================================

[!] Cannot continue due to previous errors (see above)

*** Process will exit ***
[!] Failed to update all extensions for ds3622xsp_42218 platform - see errors above

*** Process will exit ***
FAILED : Loader creation failed check the output for any errors
tc@box:~$ ^C

**Comment by klaaut** [comment]
Thanks for your kind advise.  
I understood.  As per your comment, I'll install through only one adapter.
Thank you.

**Comment by noname1001** [comment]
I am having trouble reaching my Xpenology-NAS with tcrp and an intel X540 NIC.

my setup is as following:

- VM or BareMetal : BareMetal
- Hardware (Motherboard/CPU) : MSI MPG Z390 / Intel 9900T
- Hot Plug/Hot Swap Applied : Yes
- Network Interface 1 : Intel i217v (e1000e Not working for me in xpenology)
- Network Interface 2 : Intel X540-T2 (10 Gbit)
- Network Interface 3 : Intel X540-T2 (10 Gbit)
- Loader : TCRP 0.4.6
- version of rploader.sh : 0.8.0
- Platform : DS3622xsp
- Platform Version : 7.1
- Platform Revision : 42661
- GRUB Boot selection : USB 
- Current Status  : Boots to kernel

are there known issues with that NIC?

I also tested 

- Platform : DS3617xs
- Platform Version : 7.0.1
- Platform Revision : 42218

and was able to get to the installation screen. However after installing the appropriate pat file nothing happens and even after a restart I have the same installation screen

![571068407_Bildschirmfoto2022-06-05um13_34_08 thumb png 01422f34f74cb06818fc148b3ec0cb0f](https://user-images.githubusercontent.com/52154780/172072626-6a29ec3f-fc91-47a0-be13-04f053e0218e.png)

**Comment by pocopico** [comment]
My suggestion ? Don’t waste such a powerful hardware for a single instance machine. Move to a hypervisor. If not, we can work on your issues, but I know for sure that igc (1 Gb connection) will not compile on kernels < 5.x

**Comment by noname1001** [comment]
I don't want any performance loss by hypervising, therefore I'd prefer baremetal.

Solution
-
I was able to reach the machine by unplugging the X540-T2 right after building the loader and before the DSM installation process. 

Afterwards I plugged it back in and was able to see and use it.

**Comment by noname1001** [comment]
I don't want to lose any performance to a hypervisor. I managed to get it working.

Solution
-

1. Unplug Intel X540-T2
2. Install DSM with onboard NIC (i217v -> e1000e)
3. Shutdown and plug the X540 back in.
4. Et voila!

**Comment by PeterSuh-Q3** [comment]
As pocopico mentioned above, this is only for DS3622xs+.
The DS3622xs+ DSM includes vanilla ixgbe.
So, it works even if X520-T2 is installed after DSM is installed.

**Comment by ch155260** [comment]
> As pocopico mentioned above, this is only for DS3622xs+. The DS3622xs+ DSM includes vanilla ixgbe. So, connecting X520-T2 after installing DSM will also work.

To use the ixgbe driver of the above method is workable, but LAN speed has some wrong by auto-negotiation and needs to adjust speed by manual.

I have the issue as above with Intel X550-AT2. How can I update the driver in synology or tinycore-redpill?

**Comment by PeterSuh-Q3** [comment]
> > As pocopico mentioned above, this is only for DS3622xs+. The DS3622xs+ DSM includes vanilla ixgbe. So, connecting X520-T2 after installing DSM will also work.
> 
> To use the ixgbe driver of the above method is workable, but LAN speed has some wrong by auto-negotiation and needs to adjust speed by manual.
> 
> I have the issue as above with Intel X550-AT2. How can I update the driver in synology or tinycore-redpill?


I recently discussed the existence of this driver with ARPL developer fabio. The vanilla module can be inferred from the size of the files included in the link below. If these modules are different, try replacing them yourself in the following way.

https://xpenology.com/forum/topic/65408-automated-redpill-loader-arpl/?do=findComment&comment=437865

sudo -i
rmmod ixgbe.ko
cp ixgbe.ko /lib/modules
insmod ixgbe.ko

**Comment by ch155260** [comment]
> > > As pocopico mentioned above, this is only for DS3622xs+. The DS3622xs+ DSM includes vanilla ixgbe. So, connecting X520-T2 after installing DSM will also work.
> > 
> > 
> > To use the ixgbe driver of the above method is workable, but LAN speed has some wrong by auto-negotiation and needs to adjust speed by manual.
> > I have the issue as above with Intel X550-AT2. How can I update the driver in synology or tinycore-redpill?
> 
> I recently discussed the existence of this driver with ARPL developer fabio. The vanilla module can be inferred from the size of the files included in the link below. If these modules are different, try replacing them yourself in the following way.
> 
> https://xpenology.com/forum/topic/65408-automated-redpill-loader-arpl/?do=findComment&comment=437865
> 
> sudo -i rmmod ixgbe.ko cp ixgbe.ko /lib/modules insmod ixgbe.ko

I already had try it, but still have same issue.
