### ISSUE TITLE
mlx4_core Mellanox Not Working

### ISSUE THREAD

**Issue by JohnFlorezC** [pocopico/rp-ext#104]
![Screenshot 2022-04-24 233053](https://user-images.githubusercontent.com/93020035/165026313-1a71a246-eec5-4ba9-b792-1eb2e9a7f032.jpg)

---------------------------------------------------
tc@box:~$ ./rploader.sh ext broadwell-7.0.1-42218 add https://github.com/pocopico/rp-ext/blob/main/mlx4_core/rpext-index.json
ln: failed to create symbolic link '/home/tc/custom-module/auxfiles': Operation not permitted
Rploader Version : 0.7.0.5
Loader source : https://github.com/jimmyGALLAND/redpill-load.git Loader Branch : develop
Redpill module source : https://github.com/jimmyGALLAND/redpill-lkm.git : Redpill module branch : develop
Extensions :
Extensions URL :
TOOLKIT_URL : https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.broadwell-7.0.dev.txz/download
TOOLKIT_SHA : e050987fbbab0c246aff2af935b1d8a4140ce490915aa4c92f3c8d163eea970c
SYNOKERNEL_URL : https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/broadwell-source/linux-3.10.x.txz/download
SYNOKERNEL_SHA : d3e85eb80f16a83244fcae6016ab6783cd8ac55e3af2b4240455261396e1e1be
COMPILE_METHOD : toolkit_dev
TARGET_PLATFORM       : broadwell
TARGET_VERSION    : 7.0.1
TARGET_REVISION : 42218
REDPILL_LKM_MAKE_TARGET : dev-v7
KERNEL_MAJOR : 4
MODULE_ALIAS_FILE :  modules.alias.4.json
SYNOMODEL : ds3617xs_42218
MODEL : DS3617xs
Local Cache Folder : /mnt/sdb3/auxfiles
Checking Internet Access -> OK
Redpill sources already downloaded, pulling latest
Already up to date.
Loader sources already downloaded, pulling latest
Already up to date.
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/rp-ext/blob/main/mlx4_core/rpext-index.json...
[#] Downloading remote file https://github.com/pocopico/rp-ext/blob/main/mlx4_core/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
 -=O#-   #      #       #

[-] JSON file "/home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json" is invalid:

parse error: Invalid numeric literal at line 7, column 10
[-] Extension loaded from https://github.com/pocopico/rp-ext/blob/main/mlx4_core/rpext-index.json (id: ) is invalid: index JSON file is unparsable. Please report that to the extension maintainer via help URL
[!] The index file for https://github.com/pocopico/rp-ext/blob/main/mlx4_core/rpext-index.json extension is invalid - please report that to the extension maintainer

*** Process will exit ***
----------------------------------------------------------------

Thanks!

**Comment by pocopico** [comment]
Please change your repo to  https://github.com/pocopico/redpill-load.git
