### ISSUE TITLE
Deliver a new extension

### ISSUE THREAD

**Issue by sebastienraillet** [pocopico/rp-ext#105]
Hello @pocopico 👋🏼
First, thanks for your work. It's very helpful to easily upgrade the loader.

Just to give you a bit of context, on my on side, I have a HP N54L on which I run DSM in bare metal mode. I did an upgrade from Jun's loader 6.1.x to Redpill one on 7.0.x and then 7.1 (currently I'm on _7.1-42661_). Since the 7.0.x, upgrade I've lost USB support for my USB ZWave key (but standard USB storage key are still detected).

I know that DSM7 is lacking support for USB devices but even by inserting the module **cdc_acm.ko**, I wasn't able to detect by ZWave key (through lsusb for example).

After investigation, I've discovered that DSM image is lacking **ohci-hcd.ko** kernel module which allows to manage USB 1.1 peripherals on HP N54L.

I was able to recompile it by myself and then, everything works properly 🎉.

I would like to deliver it as an extension for the others in case they are facing same issue. But I'm not sure the way I've compiled it is the right one. Do you have something to share about this topic ? 

Thanks 👍

**Comment by pocopico** [comment]
For modules to load correctly as an extension,

you should use binutils < 2.31, - I use 2.25 
you should build with the toolkit 
you should use latest provided syno kernel 

I then use a function like : 

KERNEL_SOURCE="/opt/dsm-kernel/apollolake/linux-4.4.180"
KHOME="/opt/dsm-kernel/apollolake"


###################################################################################

function dsmmake(){

make \
CROSS_COMPILE="$KHOME/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/bin/x86_64-pc-linux-gnu-" \
CFLAGS="-I$KHOME/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/" \
LDFLAGS="-I$KHOME/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/lib/" \
RANLIB="/usr/bin/x86_64-linux-gnu-ranlib" \
LD="/usr/bin/x86_64-linux-gnu-ld" \
CC="/usr/bin/x86_64-linux-gnu-gcc" \
LD_LIBRARY_PATH="$KHOME/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib" \
-C "$KHOME/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0/build/" \
ARCH=x86_64 M=`pwd` modules $@

}

And then i enter the kernel driver directory for instance : 

cd apollolake/linux-4.4.180/drivers/usb/host
and execute :  
dsmmake CONFIG_USB_OHCI_HCD=m

**Comment by coolinx** [comment]
Hi @sebastienraillet I'm a fellow HP N54L Microserver user and was missing the USB 1.1 devices like my Zigbee stick. With your driver and the DS3615XS xpenology I was able to get that functionality back, and I'm super happy with that. Many thanks!

It would however be great if you could help the community and compile that driver also for the DS3622XS+ version. I would be eternally grateful, and so will be our fellow N54L Microserver users.
