### ISSUE TITLE
tn40xx missing json file

### ISSUE THREAD

**Issue by docop** [pocopico/rp-ext#111]
Hi   Just to note on  tn40xx  , for a ds3617xs_42661 build, script do fail as no file are present on the release folder for the ds3617xs.  But it's written in the rpext-index.json file.
 Thanks in advance

**Comment by docop** [comment]
oh and also for the ds3622xsp.   thanks

**Comment by pocopico** [comment]
Updated tn40xx extension and included missing platforms
