### ISSUE TITLE
ext add request SATA and SAS 

### ISSUE THREAD

**Issue by pafaf** [pocopico/rp-ext#114]
hi, i have a HP xw8600  , it would be awesome to have  this 2 ext to rum ds3615 or ds3622.

this is what i pulled from lscpi 
11:06.0 SCSI storage controller: LSI Logic / Symbios Logic SAS1068 PCI-X Fusion-MPT SAS (rev 02)
00:1f.2 RAID bus controller: Intel Corporation 631xESB/632xESB SATA RAID Controller (rev 09)

the SAS seems to load, but i allways get error on instaling DSM , it says  problaby corrupt file !!!

regards
Pedro

**Comment by pocopico** [comment]
Corrupt pat file is 99% wrong setting of USB PID:VID. Also to be certain about the driver you should pass the line that you get with lspci -nnq

**Comment by pafaf** [comment]
You were right, 👍 somehow USB ID´s were wrong!   already installed DSM_DS3615xs_42661 on LSI CTRL sucessfuly.   i´ll try out with DS3622 42661.

I get the same info on lspci  with or without -nnq   !!
11:06.0 SCSI storage controller [0100]: LSI Logic / Symbios Logic SAS1068 PCI-X Fusion-MPT SAS [1000:0054] (rev 02)
00:1f.2 RAID bus controller [0104]: Intel Corporation 631xESB/632xESB SATA RAID Controller [8086:2682] (rev 09)

So LSI is working fine with driver scsi-5.10.3-tinycore64.tcz:

it would be nice no have this INTEL SATA RAID driver working  for faster boot.  please let me now how can i help :)

**Comment by pocopico** [comment]
Great ! Take care
