### ISSUE TITLE
Error sha256, please fix

### ISSUE THREAD

**Issue by dklabvn** [pocopico/rp-ext#115]
[#] Verifying /home/tc/redpill-load/custom/extensions/pocopico.ixgbe/dva3221_42218/ixgbe-4.4.180plus-denverton.tgz file... [ERR]
[!] Checksum mismatch - expected 54f1d2b9c11c65708429d42d1760b12922e91dfb2e32acc              cfc2748ff586e30b9 but computed 9e71adb9bc8940af18bb00087d03127fd9b01557e1967cd48              f79c8553a767574

*** Process will exit ***
[!] Failed to update all extensions for dva3221_42218 platform - see errors abov              e

*** Process will exit ***

**Comment by pocopico** [comment]
Fixed
