### ISSUE TITLE
ds1621p's  1gb intel igb / e1000e / e1000 does'n work

### ISSUE THREAD

**Issue by PeterSuh-Q3** [pocopico/rp-ext#122]
pocopico 
ds1621p's  intel 1gb igb / e1000e / e1000 does'n work
can you fix it?

It was a normal return in the junior log,
There were no special features to be seen.
If you need other logs, we will provide them.

**Comment by pocopico** [comment]
Please provide all possible logs 

/var/log/linux*
/var/log/junior*
lsmod 
dmesg

**Comment by PeterSuh-Q3** [comment]
@dolbycat's idea of igb and e1000e
Replaced v1000's ko with denverton's ko as shown in the link below.

dolbycat and i from ds1621+ to this replaced en
I checked whether the intel nic works normally.

Due to miscommunication with @dolbycat, e1000 confirmed again that there is no problem. (retest confirmed by proxmox)

So, the error log of the old ext is probably unnecessary.

Should I switch back to this successful, log?

https://github.com/dolbycat/rp-ext/blob/main/igb/releases/ds1621p_42218.json
https://github.com/PeterSuh-Q3/rp-ext/blob/main/e1000e/releases/ds1621p_42218.json

**Comment by pocopico** [comment]
Denverton and v1000 are different platforms using different kernel config files. If this works for you it’s fine. I will not replace the modules compiled for v1000 with modules compiled for denverton. 

If you want the extensions to work you have to give me the logs otherwise I will not be able to identify the problem and fix the extensions

**Comment by pocopico** [comment]
Can you please send and the output of lspci -k from an installed DSM ?

**Comment by pocopico** [comment]
The logs do not indicate any issue. I have recompiled and updated the extension for V1000. Please try again.

**Comment by PeterSuh-Q3** [comment]
The recompiled igb / e1000e ext finally started working.
It works very well.
thank you so much. pocopico. ^^
(Tested on baremetal)
