### ISSUE TITLE
Please add NetLink BCM57788 Driver，Thanks very much!

### ISSUE THREAD

**Issue by yoyopie** [pocopico/rp-ext#128]
Thanks very much!

I hava try https://github.com/pocopico/rp-ext/blob/main/tg3/rpext-index.json，but it's not work。

driver download link: https://fichiers.touslesdrivers.com/39182/linux-3.133d.zip

driver describe link: https://www.touslesdrivers.com/index.php?v_page=23&v_code=39182

this driver support: NetLink/NetXtreme BCM57xx/BCM59xx

NetLink BCM5781
NetLink BCM5784
NetLink BCM5785
NetLink BCM5786
NetLink BCM5787
NetLink BCM5788
NetLink BCM5789
NetLink BCM57780
NetLink BCM57781
NetLink BCM57785
NetLink BCM57786
NetLink BCM57788
NetLink BCM57790
NetLink BCM57791
NetLink BCM57795
NetXtreme BCM5700
NetXtreme BCM5701
NetXtreme BCM5702
NetXtreme BCM5703
NetXtreme BCM5704
NetXtreme BCM5705
NetXtreme BCM5714
NetXtreme BCM5715
NetXtreme BCM5717
NetXtreme BCM5718
NetXtreme BCM5719
NetXtreme BCM5720
NetXtreme BCM5721
NetXtreme BCM5722
NetXtreme BCM5723
NetXtreme BCM5750
NetXtreme BCM5751
NetXtreme BCM5752
NetXtreme BCM5753
NetXtreme BCM5754
NetXtreme BCM5755
NetXtreme BCM5756
NetXtreme BCM5761
NetXtreme BCM5764
NetXtreme BCM5780
NetXtreme BCM5782
NetXtreme BCM57760
NetXtreme BCM57761
NetXtreme BCM57765
NetXtreme BCM57766
NetXtreme BCM5901
NetXtreme BCM5906

**Comment by pocopico** [comment]
tg3 that is included in extension is version 3.137 can you please share an lspci -nnq from within TCRP ?

**Comment by burtal** [comment]
in 3622xs dsm  7.1.0-42661 on a Microserver gen8 baremetall install  i cannot set MTU to 9000 (jumbo) 

maybe newer drivers could fix that ?  https://www.broadcom.com/support/download-search?pg=Ethernet+Connectivity,+Switching,+and+PHYs&pf=Ethernet+Network+Adapters&pn=&pa=&po=HPE&dk=&pl=&l=false

**Comment by yoyopie** [comment]
> tg3 that is included in extension is version 3.137 can you please share an lspci -nnq from within TCRP ?

0000:04:00.0 Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetLink BCM57788 Gigabit Ethernet PCIe [14e4:1691] (rev 01)

**Comment by yongman** [comment]
Thanks for your work !
I have the same demand for support NetXtreme BCM5720 in 3617xs.

**Comment by yongman** [comment]
I compile the tg3 driver module with synology cross compile toolkit and insmod it, at last bcm5720 card come to alive!

**Comment by pocopico** [comment]
> I compile the tg3 driver module with synology cross compile toolkit and insmod it, at last bcm5720 card come to alive!

can you please share the updated sources that you've used ?

**Comment by pocopico** [comment]
> @pocopico I push the source to https://github.com/yongman/tg3-3.137q ,downloaded from vmware website.

Thanks, updated the extension !
