### ISSUE TITLE
r8125 realtek 2.5gbe module require continuous dsm install

### ISSUE THREAD

**Issue by category-9431** [pocopico/rp-ext#15]
Board has 2 LAN (r8168 internal, r8125 external).

if usb loader with r8125 module at custom.gz is used, 
DSM 25556 install in 10 minutes and then require install again.

Normal custom.gz (no add command in redpill_tool_chain)
1st: r8168
2st: r8125 (not detected)
Detect DSM installed (only one install) and login without issue.

R8125 custom.gz  (add command in redpill_tool_chain)
1st: r8168
2st: r8125 (not detected)
Not Detect DSM installed (continuous install required)

ixgbe custom.gz (add command in redpill_tool_chain)
1st: r8168
2st: r8125 (not detected)
Detect DSM installed (only one install) and login without issue.

What's wrong r8125 ext?

**Comment by pocopico** [comment]
What is the platform that you are testing ? 3615 or 918 ?

**Comment by category-9431** [comment]
apollolake-6.2.4-25556

**Comment by category-9431** [comment]
load r8125.ko OK and now login. Thanks.
