### ISSUE TITLE
Intel Corporation Ethernet Controller I225-V [8086:15f3]

### ISSUE THREAD

**Issue by snp-g** [pocopico/rp-ext#152]
Hi Picopico,

I'm trying to build xpenology on baremetal. I would say I have an issue with ethernet as satamap recognized 2 ports.

I tried existing extension igb, e1000 and e1000e but I cannot see it on the network once it is booted up (unfortunately I'm not able to get to console due to baremetal).

Could you help me , please?

`./rploader.sh listmods apollolake-7.1.0-42661
Found VGA Controller : pciid 8086d00003185  Required Extension : i915
Searching for matching extension for i915
Found SATA Controller : pciid 8086d000031e3  Required Extension :
No matching extension
Found Ethernet Interface : pciid 8086d000015f3 Required Extension :
No matching extension`

`tc@box:~$ lspci -tvnnq
-[0000:00]-+-00.0  Intel Corporation Gemini Lake Host Bridge [8086:31f0]
           +-00.1  Intel Corporation Celeron/Pentium Silver Processor Dynamic Platform and Thermal Framework Processor Participant [8086                                               :318c]
           +-02.0  Intel Corporation GeminiLake [UHD Graphics 600] [8086:3185]
           +-0e.0  Intel Corporation Celeron/Pentium Silver Processor High Definition Audio [8086:3198]
           +-0f.0  Intel Corporation Celeron/Pentium Silver Processor Trusted Execution Engine Interface [8086:319a]
           +-12.0  Intel Corporation Celeron/Pentium Silver Processor SATA Controller [8086:31e3]
           +-13.0-[01]----00.0  Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter [10ec:c821]
           +-13.1-[02]----00.0  Intel Corporation Ethernet Controller I225-V [8086:15f3]
           +-13.2-[03]--
           +-13.3-[04]--
           +-14.0-[05]--
           +-14.1-[06]--
           +-15.0  Intel Corporation Celeron/Pentium Silver Processor USB 3.0 xHCI Controller [8086:31a8]
           +-16.0  Intel Corporation Celeron/Pentium Silver Processor I2C 0 [8086:31ac]
           +-16.1  Intel Corporation Celeron/Pentium Silver Processor I2C 1 [8086:31ae]
           +-16.2  Intel Corporation Celeron/Pentium Silver Processor I2C 2 [8086:31b0]
           +-16.3  Intel Corporation Celeron/Pentium Silver Processor I2C 3 [8086:31b2]
           +-17.0  Intel Corporation Celeron/Pentium Silver Processor I2C 4 [8086:31b4]
           +-17.1  Intel Corporation Celeron/Pentium Silver Processor I2C 5 [8086:31b6]
           +-17.2  Intel Corporation Celeron/Pentium Silver Processor I2C 6 [8086:31b8]
           +-17.3  Intel Corporation Celeron/Pentium Silver Processor I2C 7 [8086:31ba]
           +-1c.0  Intel Corporation Celeron/Pentium Silver Processor SDA Standard Compliant SD Host Controller [8086:31cc]
           +-1e.0  Intel Corporation Device [8086:31d0]
           +-1f.0  Intel Corporation Celeron/Pentium Silver Processor LPC Controller [8086:31e8]
           \-1f.1  Intel Corporation Celeron/Pentium Silver Processor Gaussian Mixture Model [8086:31d4])`

`tc@box:~$ lspci
00:00.0 Host bridge: Intel Corporation Gemini Lake Host Bridge (rev 06)
00:00.1 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor Dynamic Platform and Thermal Framework Processor Participant (rev 06)
00:02.0 VGA compatible controller: Intel Corporation GeminiLake [UHD Graphics 600] (rev 06)
00:0e.0 Multimedia audio controller: Intel Corporation Celeron/Pentium Silver Processor High Definition Audio (rev 06)
00:0f.0 Communication controller: Intel Corporation Celeron/Pentium Silver Processor Trusted Execution Engine Interface (rev 06)
00:12.0 SATA controller: Intel Corporation Celeron/Pentium Silver Processor SATA Controller (rev 06)
00:13.0 PCI bridge: Intel Corporation Device 31d8 (rev f6)
00:13.1 PCI bridge: Intel Corporation Device 31d9 (rev f6)
00:13.2 PCI bridge: Intel Corporation Device 31da (rev f6)
00:13.3 PCI bridge: Intel Corporation Device 31db (rev f6)
00:14.0 PCI bridge: Intel Corporation Device 31d6 (rev f6)
00:14.1 PCI bridge: Intel Corporation Device 31d7 (rev f6)
00:15.0 USB controller: Intel Corporation Celeron/Pentium Silver Processor USB 3.0 xHCI Controller (rev 06)
00:16.0 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 0 (rev 06)
00:16.1 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 1 (rev 06)
00:16.2 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 2 (rev 06)
00:16.3 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 3 (rev 06)
00:17.0 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 4 (rev 06)
00:17.1 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 5 (rev 06)
00:17.2 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 6 (rev 06)
00:17.3 Signal processing controller: Intel Corporation Celeron/Pentium Silver Processor I2C 7 (rev 06)
00:1c.0 SD Host controller: Intel Corporation Celeron/Pentium Silver Processor SDA Standard Compliant SD Host Controller (rev 06)
00:1e.0 SD Host controller: Intel Corporation Device 31d0 (rev 06)
00:1f.0 ISA bridge: Intel Corporation Celeron/Pentium Silver Processor LPC Controller (rev 06)
00:1f.1 SMBus: Intel Corporation Celeron/Pentium Silver Processor Gaussian Mixture Model (rev 06)
01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
02:00.0 Ethernet controller: Intel Corporation Ethernet Controller I225-V (rev 01)`

**Comment by damienmillet** [comment]
u can't, Intel driver is compiled for kernels 5.x but dsm use only 4.x. I hav the same issue :/
use Proxmox or an usb adaptator who can use virtio

**Comment by snp-g** [comment]
OK, pity. Thank you
