### ISSUE TITLE
Wrong entry inside dtbpatch/rpext-index.json

### ISSUE THREAD

**Issue by agisofttm** [pocopico/rp-ext#161]
Hi @pocopico 

I found a wrong entry for DVA1622 inside dtbpatch/rpext-index.json and of course kernel cannot be build. 
Instead "dva1622_42962" there is "dva1622_42662" 

Can you please fix it

Thank you in advance

**Comment by pocopico** [comment]
Thanks ! I’ve pushed the typo fix
