### ISSUE TITLE
Please add the intel i226 network card driver

### ISSUE THREAD

**Issue by tyfzpb** [pocopico/rp-ext#176]
Please add the intel i226 network card driver. At present, only the i225 network card can be used for testing the igc driver, but the i226 cannot be used

**Comment by HughRyu** [comment]
Please Update Intel i225 ,igc driver to 1.2.1 version

**Comment by tyfzpb** [comment]
> Please Update Intel i225 ,igc driver to 1.2.1 version

Where is the igc driver to 1.2.1 version? I only see 1.2
“[Updated to latest sources 1.2.0](https://github.com/pocopico/rp-ext/commit/45b236b0e2d1526972ceae94c0c21d52f512e3d0)”

**Comment by HughRyu** [comment]
https://github.com/jim3ma/synology-igc

**Comment by pocopico** [comment]
Done !
