### ISSUE TITLE
Can you provide QLC82XX (HP NC523SFP 10G NIC) driver?

### ISSUE THREAD

**Issue by dominiaz** [pocopico/rp-ext#19]
07:00.0 Ethernet controller [0200]: QLogic Corp. cLOM8214 1/10GbE Controller [1077:8020] (rev 54)
	Subsystem: Hewlett-Packard Company NC523SFP 10Gb 2-port Server Adapter [103c:3733]
	Physical Slot: 3
	Flags: bus master, fast devsel, latency 0, IRQ 17
	Memory at fbe00000 (64-bit, non-prefetchable) [size=2M]
	Memory at fbdf0000 (64-bit, non-prefetchable) [size=64K]
	Expansion ROM at fb900000 [virtual] [disabled] [size=256K]
	Capabilities: [40] MSI-X: Enable+ Count=32 Masked-
	Capabilities: [80] Power Management version 3
	Capabilities: [88] Vital Product Data
	Capabilities: [a0] MSI: Enable- Count=1/32 Maskable- 64bit+
	Capabilities: [c0] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number fe-4e-fc-50-2c-27-d7-ff
	Kernel driver in use: qlcnic
	Kernel modules: qlcnic

**Comment by pocopico** [comment]
Please try  :

https://raw.githubusercontent.com/pocopico/rp-ext/master/qlcnic/rpext-index.json
