### ISSUE TITLE
QLC82XX (HP NC523SFP 10G NIC) - only 1 port works

### ISSUE THREAD

**Issue by dominiaz** [pocopico/rp-ext#21]
Hey,

I have HP NC523SFP 10G NIC with 2x 10G SFP+ port.

Port 1 works fine, but Port 2 doesn`t link anymore.

It works fine on DSM 6.2.3.

**Comment by pocopico** [comment]
Hi,

it looks that is linked to a firmware issue. I suggest you upgrade the card firmware

https://community.hpe.com/t5/ProLiant-Servers-ML-DL-SL/2-x-HP-NC523SFP-dual-ported-10GigE-in-one-server-but-only-one/td-p/6987296

And i will try to recompile to make sure

**Comment by dominiaz** [comment]
I have the newest card firmware - v4.20.1.

I have tried to upload phanfw.bin to /usr/lib/firmware.

Ive downloaded it from http://ftp.debian.org/debian/pool/non-free/f/firmware-nonfree/firmware-netxen_20210315-3_all.deb

**Comment by pocopico** [comment]
You should update the firmware on the card 

https://support.hpe.com/hpesc/public/swd/detail?swItemId=MTX_ccc8213b36b74d98a541cdc7bf#tab-history

**Comment by dominiaz** [comment]
> You should update the firmware on the card
> 
> https://support.hpe.com/hpesc/public/swd/detail?swItemId=MTX_ccc8213b36b74d98a541cdc7bf#tab-history

This component provides firmware version 4.20.1

I have 4.20.1 already on the card.

**Comment by pocopico** [comment]
Can you send the output of 

dmesg | grep -I qlcnic

**Comment by dominiaz** [comment]
`[   12.197015] qlcnic 0000:07:00.0: 2048KB memory map
[   12.854100] qlcnic 0000:07:00.0: Default minidump capture mask 0x1f
[   12.882439] qlcnic 0000:07:00.0: FW dump enabled
[   12.904032] qlcnic 0000:07:00.0: Supports FW dump capability
[   12.929761] qlcnic 0000:07:00.0: Driver v5.3.63, firmware v4.20.1
[   13.026363] qlcnic: 2c:27:d7:4e:fc:50: NC523SFP 10Gb 2-port Server Adapter Board Chip rev 0x54
[   13.065237] qlcnic 0000:07:00.0: using msi-x interrupts
[   13.118891] qlcnic 0000:07:00.0: eth0: XGbE port initialized
[   13.145774] qlcnic 0000:07:00.1: 2048KB memory map
[   13.244668] qlcnic 0000:07:00.1: Default minidump capture mask 0x1f
[   13.273012] qlcnic 0000:07:00.1: FW dump enabled
[   13.293862] qlcnic 0000:07:00.1: Supports FW dump capability
[   13.319375] qlcnic 0000:07:00.1: Driver v5.3.63, firmware v4.20.1
[   13.417134] qlcnic 0000:07:00.1: using msi-x interrupts
[   13.440417] qlcnic 0000:07:00.1: eth1: XGbE port initialized
[   96.695557] qlcnic 0000:07:00.0 eth0: Rx Context[0] Created, state 0x2
[   96.783595] qlcnic 0000:07:00.0 eth0: Tx Context[0x8000] Created, state 0x2
[   96.797613] qlcnic 0000:07:00.0 eth0: Tx Context[0x8008] Created, state 0x2
[   97.505957] qlcnic 0000:07:00.0 eth0: NIC Link is up
[   98.351283] qlcnic 0000:07:00.1 eth1: Rx Context[1] Created, state 0x2
[   98.810651] qlcnic 0000:07:00.1 eth1: Tx Context[0x8001] Created, state 0x2
[   98.856134] qlcnic 0000:07:00.1 eth1: Tx Context[0x8009] Created, state 0x2
`

**Comment by pocopico** [comment]
Well it looks that both ports are identified by the driver. I don’t see the problem. Maybe you are missing the Ethernet interface on the DSM GUI ? That’s another type of issue
