### ISSUE TITLE
RTL8111GR no ip on 3615xs

### ISSUE THREAD

**Issue by jdjxk** [pocopico/rp-ext#22]
I use ASRock J3455B-ITX with Realtek RTL8111GR.
It works fine on 918+, but no ip on 3615xs.
Is that a driver issue? How can I find a RTL8111GR driver on 3615?
Thank you!

**Comment by lukemin** [comment]
same issue

**Comment by pocopico** [comment]
I have recompiled and recreated the extension for  r8168/r8111 

Try the following and report back:

a. remove extension from the loader, add it again and recreate the loader with the current extension  
b. try loading manually the 3.10.108 module
