### ISSUE TITLE
918 lsi sas driver error

### ISSUE THREAD

**Issue by Cavien** [pocopico/rp-ext#23]
All 918 series LSI SAS cards cannot be found,

All 3615 series LSI SAS cards can be found

Is there a problem with the configuration file of 918?

**Comment by pocopico** [comment]
What is the issue ? Are you trying to load one of the LSI SAS extension ? Which one ?

- mptsas
- mpt2sas
- mpt3sas 

Only one of the extensions can be included in 918  loader. Either mptsas or mpt2sas/mpt3sas. mpt2sas and mpt3sas actually are the same for kernel version 4.4.x

**Comment by Cavien** [comment]
I tried again on the 3615xs. It is normal to use the mpt2sas hard disk to identify the LSI card. I can't use the mpt2sas LSI card on the 918. In all versions of the 918, I can't use the mpt2sas to identify the LSI card,

Yes, I finally found that mpt2sas and mpt3sas use the same file.

**Comment by pocopico** [comment]
Download the modules from : 

https://github.com/pocopico/4.4.180plus-modules

and try manually once to load the following modules : 

insmod scsi_transport_sas.ko
insmod libsas.ko
insmod raid_class.ko
insmod mpt3sas.ko

lsmod |grep -i mpt

mpt3sas               194218  0
raid_class              3508  1 mpt3sas
scsi_transport_sas     23996  2 mpt3sas,libsas
