### ISSUE TITLE
HPSA not work with HP P420

### ISSUE THREAD

**Issue by MelanPrince** [pocopico/rp-ext#24]
build bromolow-7.0.1-42218 with rp_helper v0.12 

not found DISK  
HP P420 Change HBA mode。ilo can found disk。

ESXI with P420 Used it not found disk

Version

使用此版本的HPSA 编译的引导，ESXI 中直通HP P420 找不到硬盘。P420 已经通道HP 的ISO 切换到直通模式。

[#] ========================================== pocopico.hpsa ==========================================
[#] Extension name: hpsa
[#] Description: Adds Driver for HP Smart Array Controller version 3.4.14-0 Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/hpsa
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/hpsa/rpext-index.json
[#] Platforms supported: ds3615xs_42218 ds3615xs_25556 ds918p_42218 ds918p_25556 ds3615xs_41222 ds918p_41890
[#] =======================================================================================

**Comment by pocopico** [comment]
P420 is listed in the module alias  ... it should work
