### ISSUE TITLE
r8169 not working

### ISSUE THREAD

**Issue by mingjing99** [pocopico/rp-ext#28]
Tried several times, just could not bring this r8159 on board network controller online, when connected the port green light is on, but amber light not flashing. Any suggestions? Thanks

**Comment by pocopico** [comment]
Boot using a live Linux distribution and get the pci Id with lspci

**Comment by mingjing99** [comment]
Thanks for reply, here is the findings
lspci -k
in Linux Distro Network card shows as
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
        Subsystem: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
        Kernel driver in use: r8169
        Kernel modules: r8169

In the DSM7 Session show as follow
0001:02:00.0 Class 0200: Device 8086:1539 (rev 03)

Please help. Thanks again for your fantastic works!

**Comment by pocopico** [comment]
***In the DSM7 Session show as follow
***0001:02:00.0 Class 0200: Device 8086:1539 (rev 03)

8086:1539 is Intel igb ** and not RTL8111 you may use igb extension or paste the lspci -kn output

**Comment by mingjing99** [comment]
run lspci -kn, same output
For other Linux distro recognize this as RTL8111 and use driver r8169, the network card is working properly
But for somehow, DSM7 session recognize as Intel igb card
you can see the previous output from different session, it is actually pointing to the same PCI address 02:00:00

Maybe I could try to use intel igb upon this card, could you please let me know how to use igb extension? Thanks!

**Comment by mingjing99** [comment]
No luck with igb card drivers loaded, I give up on this hardware, Thank you for your help! 👍
