### ISSUE TITLE
Request to add MCX342A driver

### ISSUE THREAD

**Issue by Like-Cosmos** [pocopico/rp-ext#29]

**Comment by pocopico** [comment]
Which version ?

**Comment by Like-Cosmos** [comment]
I need to DS918 7.x

**Comment by pocopico** [comment]
I cannot find the sources for this card. Could you pass some more info ?  

Mainly,

- which driver gets loaded if you boot from a live linux distro 
- lspci -kn

**Comment by Like-Cosmos** [comment]
0000:02:00.0 0200: 15b3:1003
	Subsystem: 15b3:0113
	Kernel driver in use: mlx4_core

**Comment by pocopico** [comment]
Can you try with :

 https://raw.githubusercontent.com/pocopico/rp-ext/master/mlx4_core/rpext-index.json
