### ISSUE TITLE
Please add 9pfs

### ISSUE THREAD

**Issue by Jason98881** [pocopico/rp-ext#31]
9pfs is instead of NFS for DSM app.
Moment can work with 9pfs directory from host share, avoid the limit of moment NFS directory detect.
There are ko:
https://github.com/s2k7/DSM7-modules
There is docker DSM link:
https://xpenology.com/forum/topic/7884-xpenology-runing-on-docker/page/1/

**Comment by Jason98881** [comment]
I don't know how to add them with new ext manager, please add them, thank you!

**Comment by pocopico** [comment]
I created the v9fs extension : 

https://raw.githubusercontent.com/pocopico/rp-ext/master/v9fs/rpext-index.json

**Comment by Jason98881** [comment]
> I created the v9fs extension :
> 
> https://raw.githubusercontent.com/pocopico/rp-ext/master/v9fs/rpext-index.json

It don't work with thethorgroup.virtio (https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-virtio/rpext-index.json).
Virtio ethernet isn't work, also when mount 9p, it report can't find virtio. 
Log:
9pnet: Could not find request transport: virtio
-------------------------
Can you make a full virtio support extension please? Thank you.
-------------------------
Here are all log files:
https://xpenology.com/forum/topic/45795-redpill-the-new-loader-for-624-discussion/?do=findComment&comment=258305

**Comment by Jason98881** [comment]
I have fixed it,

**Comment by xqdxqd** [comment]
It looks like 9pnet_virtio is missing ?

**Comment by NagaseKouichi** [comment]
> The real reason is ext sequence, now 9pfs can work, thank you very much!

Does 9p work on 4.4.180 kernel?
