### ISSUE TITLE
Dell HBA330

### ISSUE THREAD

**Issue by vojtechsiller** [pocopico/rp-ext#34]
Hi, 

could you add HBA330 12Gbps SAS HBA (NON-RAID) Co ntroller, please?

BR
Vojtech

**Comment by pocopico** [comment]
Can you please send the PCI ID of the card ?

**Comment by vojtechsiller** [comment]
Hi, thank you.

here are all the device parameters.

![Screenshot 2021-12-20 at 9 42 22](https://user-images.githubusercontent.com/37530503/146738016-3f9fdea2-5a1d-4f7a-905f-f7baf69ee246.png)

**Comment by pocopico** [comment]
By the module alias, it looks like mpt3sas extension is the one you are looking for

**Comment by gangsterrapper22** [comment]
Hello,

I assume I have a similar issue with a LSI 3008 HBA Card flashed in IT Mode.
When I load the mpt3sas.ko Driver then no Card is detected. It Seems that the Dell HBA330 uses the same Chipset as my card.
If I do a lscpi -k then the Card is shown as 0000:01:00.0 Class 0107: Device 1000:0097 (rev 02)
        Subsystem: Device 1000:30e which should be supported according your comment.

If I do a insmod mpt3sas.ko I see the following Message via DMESG.

[ 7950.920617] mpt3sas_cm0: 64 BIT PCI BUS DMA ADDRESSING SUPPORTED, total mem (16227156 kB)
[ 7950.928796] mpt3sas_cm0: unable to map adapter memory!  or resource not found
[ 7950.935941] Trying to free nonexistent resource <00000000df240000-00000000df24ffff>
[ 7950.943609] Trying to free nonexistent resource <00000000df200000-00000000df23ffff>
[ 7950.951260] mpt3sas_cm0: failure at /linux/syno/linux/apollolake/drivers/scsi/mpt3sas/mpt3sas_scsih.c:8781/_scsih_probe()!

I use the redpill loader and DSM 6.2.4 25556 as Apollolake. Could this maybe the issue?

Thank you.

**Comment by pocopico** [comment]
Mpt3sas extension had been updated please try again
