### ISSUE TITLE
r8125b install success, but then reboot can't get the ip

### ISSUE THREAD

**Issue by yyaocsyy** [pocopico/rp-ext#35]
Hi,

Thanks for your all work for rp drivers.
my HW config
```
MB: MSI H510i pro wifi with rtl8125b
CPU: i3-10105
```

I compiled apollolake-7.0.0-41890 img with lastest [r8125](https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json) , [acpid](https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json) and [early-telent](https://github.com/pocopico/rp-ext/raw/main/early-telnet/rpext-index.json)

I can success install the 41890 on by PC by 8125B 2.5G , but after successful install, the machine can't auto reboot.
Then I force power down and then power up, I found that I can't get the IP. I can do nothing for the NAS.

But once when I formatting the SATA on other PC, I can find the PC can install the NAS again.

SO it seems once I install the NAS success, then I can;t get the IP.
But I can get the IP during the install stage.

**Comment by pocopico** [comment]
OK, try with the minimum extensions. e.g. only r8125 and start adding one by one to see which one is causing you problems.
