### ISSUE TITLE
918 LSI 2308 The requirement drive status is not met

### ISSUE THREAD

**Issue by hdbai** [pocopico/rp-ext#36]
RedPill-TTG/redpill-lkm#26

encounter the same issue. I am using a IBM ServRAID M5110 RAID card flashed to IT HBA Mode.  
I load the driver via your suggestion in #23, but no luck for that.

**Comment by pocopico** [comment]
Can you please sent the output of lspci -nnq

**Comment by hdbai** [comment]
Thanks for the reply.
`root@dsm701:~# lspci -nnq
0000:00:00.0 Host bridge [0600]: Intel Corporation 82G33/G31/P35/P31 Express DRA                     M Controller [8086:29c0]
0000:00:01.0 VGA compatible controller [0300]: Red Hat, Inc. QXL paravirtual gra                     phic card [1b36:0100] (rev 05)
0000:00:02.0 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
0000:00:02.1 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
0000:00:02.2 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
0000:00:02.3 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
0000:00:07.0 USB controller [0c03]: Red Hat, Inc. QEMU XHCI Host Controller [1b3                     6:000d] (rev 01)
0000:00:1f.0 ISA bridge [0601]: Intel Corporation 82801IB (ICH9) LPC Interface C                     ontroller [8086:2918] (rev 02)
0000:00:1f.2 SATA controller [0106]: Intel Corporation 82801IR/IO/IH (ICH9R/DO/D                     H) 6 port SATA Controller [AHCI mode] [8086:2922] (rev 02)
0000:00:1f.3 SMBus [0c05]: Intel Corporation 82801I (ICH9 Family) SMBus Controll                     er [8086:2930] (rev 02)
0000:01:00.0 Ethernet controller [0200]: Red Hat, Inc. Virtio network device [1a                     f4:1041] (rev 01)
0000:02:00.0 Communication controller [0780]: Red Hat, Inc. Virtio console [1af4                     :1043] (rev 01)
**0000:03:00.0 Serial Attached SCSI controller [0107]: Broadcom / LSI SAS2308 PCI-                     Express Fusion-MPT SAS-2 [1000:0087] (rev 05)**
0001:00:12.0 SATA controller [0106]: Intel Corporation Celeron N3350/Pentium N42                     00/Atom E3900 Series SATA AHCI Controller [8086:5ae3]
0001:00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Celeron N3350                     /Pentium N4200/Atom E3900 Series PCI Express Port A #1 [8086:5ad8]
0001:00:14.0 Non-VGA unclassified device [0000]: Intel Corporation Celeron N3350                     /Pentium N4200/Atom E3900 Series PCI Express Port B #1 [8086:5ad6]
0001:00:15.0 USB controller [0c03]: Intel Corporation Celeron N3350/Pentium N420                     0/Atom E3900 Series USB xHCI [8086:5aa8]
0001:00:16.0 Signal processing controller [1180]: Intel Corporation Celeron N335                     0/Pentium N4200/Atom E3900 Series I2C Controller #1 [8086:5aac]
0001:00:18.0 Signal processing controller [1180]: Intel Corporation Celeron N335                     0/Pentium N4200/Atom E3900 Series HSUART Controller #1 [8086:5abc]
0001:00:19.0 Signal processing controller [1180]: Intel Corporation Celeron N335                     0/Pentium N4200/Atom E3900 Series SPI Controller #3 [8086:5ac6]
0001:00:19.2 Signal processing controller [1180]: Intel Corporation Celeron N335                     0/Pentium N4200/Atom E3900 Series SPI Controller #3 [8086:5ac6]
0001:00:1f.0 SMBus [0c05]: Intel Corporation Celeron N3350/Pentium N4200/Atom E3                     900 Series SMBus Controller [8086:5ad4]
0001:00:1f.1 SMBus [0c05]: Intel Corporation Celeron N3350/Pentium N4200/Atom E3                     900 Series SMBus Controller [8086:5ad4]
0001:01:00.0 SATA controller [0106]: Marvell Technology Group Ltd. 88SE9215 PCIe                      2.0 x1 4-port SATA 6 Gb/s Controller [1b4b:9215] (rev 11)
0001:02:00.0 Ethernet controller [0200]: Intel Corporation I211 Gigabit Network                      Connection [8086:1539] (rev 03)
0001:03:00.0 Ethernet controller [0200]: Intel Corporation I211 Gigabit Network                      Connection [8086:1539] (rev 03)
`
`root@dsm701:~# dmesg | grep RedPill
[    0.539840] <redpill/redpill_main.c:46> RedPill v0.5-git-6a969da loading...
[    0.822070] <redpill/redpill_main.c:69> RedPill v0.5-git-6a969da loaded successfully (stealth=1)
`

**Comment by pocopico** [comment]
Are you using the latest RedPill ? This seems like an old issue

**Comment by hdbai** [comment]
the loader is built from a github action from [s1oz/redpill-loader-action](https://github.com/hdbai?tab=repositories)
from his build-ds918-7.0.1.sh

```
#!/bin/bash

# prepare build tools
sudo apt-get update && sudo apt-get install --yes --no-install-recommends ca-certificates build-essential git libssl-dev curl cpio bspatch vim gettext bc bison flex dosfstools kmod jq

root=`pwd`
mkdir ds918-7.0.1
mkdir output
cd ds918-7.0.1

# download redpill
git clone --depth=1 https://github.com/RedPill-TTG/redpill-lkm.git
git clone -b develop --depth=1 https://github.com/jumkey/redpill-load.git

# download syno toolkit
curl --location "https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.apollolake-7.0.dev.txz/download" --output ds.apollolake-7.0.dev.txz

mkdir apollolake
tar -C./apollolake/ -xf ds.apollolake-7.0.dev.txz usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0/build

# build redpill-lkm
cd redpill-lkm
make LINUX_SRC=../apollolake/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0/build dev-v7
read -a KVERS <<< "$(sudo modinfo --field=vermagic redpill.ko)" && cp -fv redpill.ko ../redpill-load/ext/rp-lkm/redpill-linux-v${KVERS[0]}.ko || exit 1
cd ..

# build redpill-load
cd redpill-load
cp ${root}/user_config.DS918+.json ./user_config.json
sudo ./build-loader.sh 'DS918+' '7.0.1-42218'
mv images/redpill-DS918+_7.0.1-4221*.img ${root}/output/
cd ${root}
```
where
```
# download redpill
git clone --depth=1 https://github.com/RedPill-TTG/redpill-lkm.git
git clone -b develop --depth=1 https://github.com/jumkey/redpill-load.git
```

 ** --depth=1** is included, so I assume  it's the latest loader of RedPill

**Comment by pocopico** [comment]
Oh ok 
. Where do you add the extensions after that?

**Comment by hdbai** [comment]
Still in build-ds918-7.0.1.sh
I changed this part
```
# build redpill-load
cd redpill-load
cp ${root}/user_config.DS918+.json ./user_config.json
sudo ./build-loader.sh 'DS918+' '7.0.1-42218'
mv images/redpill-DS918+_7.0.1-4221*.img ${root}/output/
cd ${root}
```
to
```
# build redpill-load
cd redpill-load
cp ${root}/user_config.DS918+.json ./user_config.json

./ext-manager.sh add https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-virtio/rpext-index.json
./ext-manager.sh add https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-acpid/rpext-index.json
./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/vmxnet3/rpext-index.json
./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/e1000e/rpext-index.json
./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/igb/rpext-index.json
./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/ixgbe/rpext-index.json
./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8125/rpext-index.json

sudo ./build-loader.sh 'DS918+' '7.0.1-42218'
mv images/redpill-DS918+_7.0.1-4221*.img ${root}/output/
cd ${root}
```

for mpt3sas.ko, I added it manually via #23
