### ISSUE TITLE
adding mpt2sas/mpt3sas to apollolake-7.0.1-42218 stops vmxnet3 and VMware virtual disks from working

### ISSUE THREAD

**Issue by Byolock** [pocopico/rp-ext#38]
I have got an working image with vmxnet3 running on my esxi server, if I add mpt2sas/mpt3sas  driver to this image I'm not able to reach the virtual machine anymore. This can be fixed by changing the network adapter back to E1000e so there seems to be an issue with the vmxnet3 module when i load mpt2sas. 

In addition there is some problem with vmware virtual disks after adding mpt2sas :
Although DSM is already installed on the virtual drives that installation isn't found and the web assistant prompts for installation of DSM, if I follow this along, after uploading the .pat file the web assistant says its going to reboot. After this reboot the web page brings me back to the installation prompt. I also noticed that the normal "Data on Disks 1,2 are going to be deleted" warning in the installation routine is missing.

I've attached the serial log of booting an image with vmxnet3 & mpt2sas, installing DSM and letting it reboot till i get the install prompt again. 

[serial_log.txt](https://github.com/pocopico/rp-ext/files/7785615/serial_log.txt)

If you need any more information please let me know.

**Comment by pocopico** [comment]
Ok error relies here :  


Loading kmod #2 "mpt3sas.ko" for poco[   11.249231] mpt3sas: Unknown rela relocation: 4
pico.mpt2sas (args: )
[   11.255615] mpt3sas: Unknown rela relocation: 4
insmod: can't insert 'mpt3sas.ko': invalid module format
ERROR: kernel extensions "mpt3sas.ko" from pocopico.mpt2sas failed to load
Exit on error [99] rp ext init exec failure...
Tue Dec 28 16:26:17 UTC 2021


Let me check and I’ll come back to you

**Comment by pocopico** [comment]
Mpt3sas ext recreated

**Comment by Byolock** [comment]
Unfourtanetly this did not fix my issue, got the same Error message again:
```
:: Loading kernel modules from extensions ...
Loading kmod #0 "raid_class.ko" for pocopico.mpt3sas (args: )
Loading kmod [   11.137936] mpt3sas: Unknown rela relocation: 4
#1 "scsi_transport_sas.ko" for pocopico.mpt3sas (args: )
Loading kmod #2 "mpt3sas.ko" for pocopico.mpt3sas (args: )
[   11.154229] mpt3sas: Unknown rela relocation: 4
insmod: can't insert 'mpt3sas.ko': invalid module format
ERROR: kernel extensions "mpt3sas.ko" from pocopico.mpt3sas failed to load
Exit on error [99] rp ext init exec failure...
Mon Jan 17 10:45:30 UTC 2022
none /sys/kernel/debug debugfs rw,relatime 0 0
umount: /etc/mtab: No such file or directory

linuxrc.syno failed on 99
```

**Comment by pocopico** [comment]
I have recompiled. I think i have fixed that now. could you please retry ?

**Comment by Byolock** [comment]
Looks at least way better, maybe fixed:

```
:: Loading kernel modules from extensions ...
Loading kmod #0 "raid_class.ko" for pocopico.mpt3sas (args: )
Loading kmod #1 "scsi_transport_sas.ko" for pocopico.mpt3sas (args: )
Loading kmod #2 "mpt3sas.ko" for pocopico.mpt3sas (args: )
[   11.094759] mpt3sas version 22.00.00.00 loaded
Loading kmod #0 "vmxnet3.ko" for po[   11.100665] VMware vmxnet3 virtual NIC driver - version 1.4.5.0-k-NAPI
copico.vmxnet3 (args: )
:: Loading kernel modules from extensions ... [  OK  ]
:: Executing "on_boot" custom scripts ...
Running "check-mpt3sas.sh" for pocopico.mpt3sas->on_boot
Loading module mpt3sas -> Module mpt3sas is not loaded 
Ran "check-mpt3sas.sh" for pocopico.mpt3sas->on_boot - exit=0
Running "check-vmxnet3.sh" for pocopico.vmxnet3->on_boot
Loading module vmxnet3 -> Module vmxnet3 loaded succesfully
Ran "check-vmxnet3.sh" for pocopico.vmxnet3->on_boot - exit=0
Running "boot-wait.sh" for thethorgroup.boot-wait->on_boot
Confirmed a valid-looking /dev/synoboot device
Ran "boot-wait.sh" for thethorgroup.boot-wait->on_boot - exit=0
:: Executing "on_boot" custom scripts ... [  OK  ]
Extensions processed
```

Is the line `Loading module mpt3sas -> Module mpt3sas is not loaded` expected?  I've need to finish backup my data before actually attaching the raid controller. So maybe the Module does not load because there is no hardware which needs it?

**Comment by pocopico** [comment]
the exit=0 so its fine.
