### ISSUE TITLE
Please add i40evf for sriov of i40e

### ISSUE THREAD

**Issue by lunerseayu** [pocopico/rp-ext#42]
x710 works pretty good but when i use sriov，it's does not work. the sriov dirver of i40e is i40evf. and here is the website to download.
[https://www.intel.com/content/www/us/en/download/18159/intel-network-adapter-linux-virtual-function-driver-for-intel-ethernet-controller-700-and-e810-series.html](url)

**Comment by pocopico** [comment]
latest version on the link you provided is iavf-x.x.x.tar.gz ... is that what you are looking for ?

**Comment by naoki66** [comment]
ID  18159   Date 12/22/2021   Version  4.3.19 (Latest)
This release includes iavf Linux* Virtual Function Drivers for Intel® Ethernet Network Connections.

The iavf driver supports devices based on the following controllers:

Intel® Ethernet Controller E810-C
Intel® Ethernet Controller X710
Intel® Ethernet Controller XL710
Intel® Ethernet Network Connection X722
Intel® Ethernet Controller XXV710
Intel® Ethernet Controller V710

**Comment by naoki66** [comment]
https://github.com/pocopico/4.4.180plus-modules/blob/main/i40evf.ko

**Comment by lunerseayu** [comment]
thank you so much!!!!
