### ISSUE TITLE
Request for adding ata_piix

### ISSUE THREAD

**Issue by niko44** [pocopico/rp-ext#46]
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
[!] Failed to download https://raw.githubusercontent.com/pocopico/rp-ext/master/ata_piix/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json

*** Process will exit ***

[!] Failed to add "https://raw.githubusercontent.com/pocopico/rp-ext/master/ata_piix/rpext-index.json" as an extension:

,

*** Process will exit ***
Found IDE Controller : pciid 8086d00007111  Required Extension : ata_piix
ata_piix
Searching for matching extension for ata_piix
Found matching extension : 
"https://raw.githubusercont

**Comment by pocopico** [comment]
The ata_piix has been recalled due to issues with libata
