### ISSUE TITLE
编译 "apollolake 7.0.1-42218" hpsa

### ISSUE THREAD

**Issue by 1034299619** [pocopico/rp-ext#61]
![微信截图_20220217170921](https://user-images.githubusercontent.com/63936754/154442841-0e070198-2a94-4a8f-ad73-4fb9e54ec247.png)

**Comment by jiuxiaofu** [comment]
me too

**Comment by jiuxiaofu** [comment]
您好，受累问一下，我使用HP H240 阵列卡直通，是只安装HPSA的驱动就可以还是需要在安装其他阵列卡芯片的驱动？

**Comment by pocopico** [comment]
Fixed
