### ISSUE TITLE
Please add  Broadcom BCM57788

### ISSUE THREAD

**Issue by qingshuiqingliu** [pocopico/rp-ext#69]
Hello,

If you could add drivers for Broadcom BCM57788 it will be very nice for me :)

Thanks

**Comment by recoco** [comment]
tg3 ext module should works.

**Comment by Eagle233Real** [comment]
> tg3 ext module should works.

It doesn't work

**Comment by pocopico** [comment]
Latest recompiled version tg3 with driver version  3.137q should work
