### ISSUE TITLE
Found SATA Controller : pciid 1022d00007901 

### ISSUE THREAD

**Issue by Ssyleric** [pocopico/rp-ext#71]
Hello,
Can i have this extension for this MB,  please?
Motherboard MSI TRX40 PRO 10G
Found SATA Controller : pciid 1022d00007901  Required Extension : 
No matching extension
Found SATA Controller : pciid 1022d00007901  Required Extension : 
No matching extension

SATA controller [0106]: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] [1022:7901] (rev 51)

**Comment by pocopico** [comment]
Already part of the AHCI module.
