### ISSUE TITLE
the alx driver for ds918p-7.0.1-42218 has problem with Qualcomm Atheros QCA8171

### ISSUE THREAD

**Issue by SyraTi** [pocopico/rp-ext#78]
the serial out put shows 
```shell
:: Loading kernel modules from extensions ...
Loading kmod #0 "alx.ko" for pocopico.alx (args: )
[    2.676549] alx: Unknown symbol mdio_mii_ioctl (err 0)
[    2.689257] alx: Unknown symbol mdio_mii_ioctl (err 0)
insmod: can't insert 'alx.ko': unknown symbol in module, or unknown parameter
ERROR: kernel extensions "alx.ko" from pocopico.alx failed to load
```

**Comment by SyraTi** [comment]
the QCA8171 cannot be detected, and finally can not get ip. can someone help me?

**Comment by SyraTi** [comment]
found reason why.  mdbio was missing for ds918p , I'll make a pr soon.

**Comment by buzai** [comment]
How did you get the serial output? I also need an ALX driver, but it doesn't work all the time. I can't see the IP assigned to the machine in the router, so I think the driver must not succeed, but the previous 1.03B +6.2.3 has been ok. But I can't see any logs on my laptop screen. I tested it on an old laptop

**Comment by buzai** [comment]
What is your processor, I'm having some problems

**Comment by SyraTi** [comment]
> What is your processor, I'm having some problems

This issue may not be related to any cpu problems and should have been fixed and closed, but I'm still willing to say my processor is G1840T.

**Comment by buzai** [comment]
Thanks for your reply, I have the same driver for my NIC. I just wanted to confirm that the Lenovo laptop contains some custom special hardware that causes my machine to not drive. By the way my processor is i5 3230M (Y400 Lenovo).

**Comment by SyraTi** [comment]
> Thanks for your reply, I have the same driver for my NIC. I just wanted to confirm that the Lenovo laptop contains some custom special hardware that causes my machine to not drive. By the way my processor is i5 3230M (Y400 Lenovo).

Maybe you should try to get the serial-port output to diagnose your problem.
