### ISSUE TITLE
r8125，ixgbe not work 

### ISSUE THREAD

**Issue by xinsui01** [pocopico/rp-ext#8]
Hi,
 Thanks for your all work for rp drivers.
 
 my HW config is:

    MB: msi b560M with rtl8125b
    CPU: i5-10400
    Nic: intel x520 82599

I compiled apollolake-7.0.1-42218 img with [tossp's redpill-tool-chain](https://github.com/tossp/redpill-tool-chain) at yesterday, and add driver r8125 and ixgbe follow tool-chain step. 
I can't find IP neither with r8125 or with ixgbe, and I can see the grub interface. Is there any problem with the img I compiled or the driver is not compatible?

**Comment by xinsui01** [comment]
@pocopico I made a img for each driver.

**Comment by xinsui01** [comment]
One more question, what is the difference between ixgbe and ixgbevf drivers? I found some relevant information online but didn't understand it. Does the intel x520 82599 network card only need to load the ixgbe driver?

**Comment by pocopico** [comment]
Yes but you can check with a live Linux distro

**Comment by pocopico** [comment]
I will test it myself tomorrow and I will update you
